# Generated by Django 5.1.4 on 2025-01-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRISON', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=15, unique=True)),
                ('mdp', models.CharField(max_length=15)),
                ('territoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRISON.territoire')),
            ],
        ),
    ]
