# Generated by Django 5.2 on 2025-06-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERS_AUTH', '0001_initial'),
        ('PRISON', '0004_alter_instance_libelle_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='territoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRISON.territoire'),
        ),
    ]
