# Generated by Django 5.1.4 on 2025-01-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_Grade', models.CharField(choices=[("PRES. DE LA COUR D'APPEL", "PRES. DE LA COUR D'APPEL"), ("CONS. DE LA COUR D'APPEL", "CONS. DE LA COUR D'APPEL"), ('JUGE DE GRANDE INSTANCE', 'JUGE DE GRANDE INSTANCE'), ('JUGE DE PAIX', 'JUGE DE PAIX'), ("PROC. GEN. PRE LA COUR D'APPEL", "PROC. GEN. PRE LA COUR D'APPEL"), ('PROC. DE LA REP. PRE LE T.G.I', 'PROC. DE LA REP. PRE LE T.G.I'), ('PROC. DE PAIX', 'PROCUREUR DE PAIX'), ('MAGISTRAT ADMINISTRATIF', 'MAGISTRAT ADMINISTRATIF')], default="PRES. DE LA COUR D'APPEL", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_Instance', models.CharField(choices=[("COURS D'APPEL", "COURS D'APPEL"), ('TRIBUNAL DE GRANDE INSTANCE', 'TRIBUNAL DE GRANDE INSTANCE'), ('TRIBUNAL DE PAIX', 'TRIBUNAL DE PAIX'), ("PARUET PRE LA COUR D'APPEL", "PARUET PRE LA COUR D'APPEL"), ('PARQUET PRE LE TRIBUNAL DE GRANDE INSTANCE', 'PARQUET PRE LE TRIBUNAL DE GRANDE INSTANCE'), ('PARQUE PRE LE TRIBUNAL DE PAIX', 'PARQUE PRE LE TRIBUNAL DE PAIX')], default="COURS D'APPEL", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('KASANGULU', 'KASANGULU'), ('MADIMBA', 'MADIMBA'), ('LUKULA', 'LUKULA'), ('MBANZA-NGUNGU', 'MBANZA-NGUNGU'), ('SONGOLOLO', 'SONGOLOLO'), ('LUOZI', 'LUOZI'), ('KIMVULA', 'KIMVULA'), ('SEKEBANZA', 'SEKEBANZA'), ('TSHELA', 'TSHELA'), ('MOANDA', 'MOANDA'), ('MATADI', 'MATADI'), ('BOMA', 'BOMA')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Agent', models.CharField(max_length=15)),
                ('postnom_Agent', models.CharField(max_length=15)),
                ('prenom_Agent', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=50)),
                ('fonction', models.CharField(default='Fonction par défaut', max_length=50)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRISON.grade')),
                ('instance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PRISON.instance')),
            ],
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_prison', models.CharField(max_length=15)),
                ('capacite', models.IntegerField()),
                ('directeur', models.CharField(max_length=15)),
                ('territoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRISON.territoire')),
            ],
        ),
    ]
