# Generated by Django 5.1.4 on 2025-01-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRISON', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fonction',
        ),
        migrations.AddField(
            model_name='agent',
            name='localite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PRISON.territoire'),
        ),
    ]
