# Generated by Django 5.1.4 on 2025-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRISON', '0002_remove_agent_adresse_remove_agent_fonction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='grade',
            field=models.CharField(choices=[("PRES. DE LA COUR D'APPEL", "PRES. DE LA COUR D'APPEL"), ("CONS. DE LA COUR D'APPEL", "CONS. DE LA COUR D'APPEL"), ('JUGE DE GRANDE INSTANCE', 'JUGE DE GRANDE INSTANCE'), ('JUGE DE PAIX', 'JUGE DE PAIX'), ("PROC. GEN. PRE LA COUR D'APPEL", "PROC. GEN. PRE LA COUR D'APPEL"), ('PROC. DE LA REP. PRE LE T.G.I', 'PROC. DE LA REP. PRE LE T.G.I'), ('PROC. DE PAIX', 'PROCUREUR DE PAIX'), ('MAGISTRAT ADMINISTRATIF', 'MAGISTRAT ADMINISTRATIF')], max_length=50),
        ),
    ]
