# Generated by Django 5.2 on 2025-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRISON', '0003_alter_agent_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='libelle_Instance',
            field=models.CharField(choices=[("COURS D'APPEL", "COURS D'APPEL"), ('TRIBUNAL DE GRANDE INSTANCE', 'TRIBUNAL DE GRANDE INSTANCE'), ('TRIBUNAL DE PAIX', 'TRIBUNAL DE PAIX'), ("PARQUET PRE LA COUR D'APPEL", "PARUET PRE LA COUR D'APPEL"), ('PARQUET PRE LE TRIBUNAL DE GRANDE INSTANCE', 'PARQUET PRE LE TRIBUNAL DE GRANDE INSTANCE'), ('PARQUE PRE LE TRIBUNAL DE PAIX', 'PARQUE PRE LE TRIBUNAL DE PAIX')], default="COURS D'APPEL", max_length=50),
        ),
    ]
