# Generated by Django 5.1.4 on 2025-01-18 12:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRISON', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('postnom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('profil', models.FileField(upload_to='photo_detenus')),
                ('matricule', models.CharField(default=None, max_length=15, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], default=None, max_length=15)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=500)),
                ('peine', models.CharField(choices=[('A MORT', 'A MORT'), ('CAPITALE', 'CAPITALE'), ('TRAVAUX FORCES', 'TRAVAUX FORCES')], default=None, max_length=20)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('cellule', models.CharField(max_length=15)),
                ('dossier', models.FileField(default=1, upload_to='dossier_detenu')),
                ('est_libere', models.BooleanField(default=False)),
                ('duree', models.CharField(blank=True, max_length=50, null=True)),
                ('condamne_par', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PRISON.agent')),
                ('prison_incarceree', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PRISON.prison')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField(default=datetime.date.today)),
                ('ancienne_prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancienne_prison', to='PRISON.prison')),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DETENUS.detenu')),
                ('nouvelle_prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouvelle_prison', to='PRISON.prison')),
            ],
        ),
    ]
