# Generated by Django 5.1.4 on 2025-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DETENUS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='dossier_detenu')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detenu',
            name='dossier',
        ),
        migrations.AddField(
            model_name='detenu',
            name='dossiers',
            field=models.ManyToManyField(blank=True, to='DETENUS.dossier'),
        ),
    ]
